version: '3'
services:
  webapp:
    build: .
    command: webpack-dev-server --host 0.0.0.0 --port 8000
    ports:
    - "8000:8000"
    volumes:
    - ./src:/webapp/src
    - ./static:/webapp/static
  api:
    build: ./stub-api
    command: node api.js
    ports:
    - "4000:4000"
    volumes:
    - ./stub-api/db.json:/api/db.json
